In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import scipy as sp
import IPython
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [12]:
print('fsf')

fsf


In [13]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()
print("cancer.keys(): \n {}".format(cancer.keys()))


cancer.keys(): 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(cancer['data'],cancer['target'],stratify=cancer.target,random_state=66)

norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X_train)  # learns mean, variance
X_train = norm_l(X_train)
X_test = norm_l(X_test)
# Y_train = norm_l(Y_train)
# Y_test = norm_l(Y_test)



In [158]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        tf.keras.Input(shape=(30,)),
        Dense(25, activation='relu', name = 'layer1'),
        Dense(10, activation='relu', name = 'layer2'),
        Dense(3, activation='relu', name = 'layer3'),
        Dense(1, activation='sigmoid', name = 'layer4'),
    ]
)

In [159]:
model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 25)                775       
                                                                 
 layer2 (Dense)              (None, 10)                260       
                                                                 
 layer3 (Dense)              (None, 3)                 33        
                                                                 
 layer4 (Dense)              (None, 1)                 4         
                                                                 
Total params: 1,072
Trainable params: 1,072
Non-trainable params: 0
_________________________________________________________________


In [160]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    X_train,Y_train,            
    epochs=10,
)

Epoch 1/10
14/14 [==============================] - 3s 8ms/step - loss: 0.3039
Epoch 2/10
14/14 [==============================] - 0s 9ms/step - loss: 0.0810
Epoch 3/10
14/14 [==============================] - 0s 11ms/step - loss: 0.0445
Epoch 4/10
14/14 [==============================] - 0s 9ms/step - loss: 0.0358
Epoch 5/10
14/14 [==============================] - 0s 10ms/step - loss: 0.0283
Epoch 6/10
14/14 [==============================] - 0s 10ms/step - loss: 0.0224
Epoch 7/10
14/14 [==============================] - 0s 7ms/step - loss: 0.0188
Epoch 8/10
14/14 [==============================] - 0s 7ms/step - loss: 0.0197
Epoch 9/10
14/14 [==============================] - 0s 9ms/step - loss: 0.0130
Epoch 10/10
14/14 [==============================] - 0s 9ms/step - loss: 0.0157


In [161]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [162]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")
yhat = yhat.astype(np.int)
print(yhat)

decisions = 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1

C:\Users\Gulistan Khan\AppData\Local\Temp\ipykernel_13952\665221027.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  yhat = yhat.astype(np.int)


In [163]:
# for i in range(len(yhat)):
print("prediction target name: {}".format(cancer['target_names'][yhat[:]]))

prediction target name: [['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['malignant']
 ['malignant']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['malignant']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['malignant']
 ['malignant']
 ['malignant']
 ['benign']
 ['malignant']
 ['malignant']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['benign']
 ['malignant']
 ['malignant']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['benign']
 ['malignant']
 ['malignant']
 ['malignant']
 ['benign']
 ['malignant']
 ['benign'

In [164]:
print('score : {:.2f}'.format(model.evaluate(X_test,Y_test)))

5/5 [==============================] - 0s 5ms/step - loss: 0.1785
score : 0.18


In [165]:
print("Test set score: {:.2f}".format(np.mean(yhat == Y_test)))

Test set score: 0.54
